// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.

export const environment = {
  production: true,
  WEB_API_URL: "https://www.benisflower.com/benis-api",
  GRANT_TYPE: "password",
  CLIENT_KEY: "Z0f0xnCNLLlC67ie9tHsD5gXIWZpWS7G9or5EzTI",
  CLIENT_ID: "2",
  CLIENT_SECRET: "Z0f0xnCNLLlC67ie9tHsD5gXIWZpWS7G9or5EzTI",
  SCOPE: "*",
  CDN: "https://www.cdn.benisflower.com/_uploads/pic",
};
