// Generated by https://quicktype.io

export interface ProductApi {
    data:   Product[];
    status: boolean;
}

export interface Product {
    name:      string;
    isdeleted: number;
    image:     string;
    cleanurl:  string;
    url:       string;
    imageurl:  string;
    pivot:     Pivot;
}

export interface Pivot {
    customer_id: number;
    product_id:  number;
}
